# Generated by Django 4.1.2 on 2022-11-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='fk_user',
            new_name='user',
        ),
    ]
