# Generated by Django 4.1.2 on 2022-11-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_fkkelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='namakelas',
            new_name='nama',
        ),
    ]
