# Generated by Django 4.1.2 on 2022-11-28 00:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0006_rename_namakelas_kelas_nama'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fkKelas',
            new_name='User_Kelas',
        ),
    ]
