# Generated by Django 4.1.2 on 2022-11-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_rename_fkkelas_user_kelas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Kelas',
        ),
    ]
