# Generated by Django 4.1.2 on 2022-11-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_remove_kelas_nama_kelas_kelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='kelas',
            new_name='nama',
        ),
    ]
