# Generated by Django 4.1.2 on 2022-11-28 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0011_rename_kelas_kelas_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_kelas',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.kelas'),
        ),
        migrations.AlterField(
            model_name='user_kelas',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
