# Generated by Django 4.1.2 on 2022-11-29 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0013_alter_user_kelas_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_kelas',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.kelas'),
        ),
        migrations.AlterField(
            model_name='user_kelas',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profil_Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('nim', models.IntegerField(max_length=20, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('bakat', models.CharField(max_length=200, null=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
