# Generated by Django 4.1.2 on 2022-11-29 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0014_alter_user_kelas_kelas_alter_user_kelas_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, null=True)),
                ('skill', models.CharField(max_length=200, null=True)),
                ('pbb1', models.CharField(max_length=200, null=True)),
                ('pbb2', models.CharField(max_length=200, null=True)),
                ('pengusul', models.CharField(max_length=200, null=True)),
                ('laboratorium', models.CharField(max_length=200, null=True)),
                ('jml_mhs', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('nik', models.IntegerField(max_length=20, null=True)),
                ('kode_dosen', models.CharField(max_length=5, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('keahlian', models.CharField(max_length=200, null=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
