# Generated by Django 4.1.2 on 2022-11-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_proposal_profil_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='laboratorium',
            new_name='lab',
        ),
        migrations.AddField(
            model_name='proposal',
            name='penelitian_sebelumnya',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profil_mahasiswa',
            name='nim',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profil_staff',
            name='nik',
            field=models.IntegerField(null=True),
        ),
    ]
