# Generated by Django 4.1.2 on 2022-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_rename_laboratorium_proposal_lab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='jml_mhs',
            field=models.IntegerField(null=True),
        ),
    ]
