# Generated by Django 4.1.2 on 2022-11-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0018_alter_proposal_jml_mhs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='jml_mhs',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
