# Generated by Django 4.1.2 on 2022-11-30 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0022_alter_proposal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('nim', models.IntegerField(null=True)),
                ('fakultas', models.CharField(max_length=200, null=True)),
                ('revisi', models.FileField(max_length=200, upload_to='pdf/')),
                ('lembar_ta', models.FileField(max_length=200, upload_to='pdf/')),
                ('jurnal', models.FileField(max_length=200, upload_to='pdf/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
