# Generated by Django 4.1.2 on 2022-12-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0023_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='jurnal',
            field=models.FileField(blank=True, max_length=200, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='lembar_ta',
            field=models.FileField(blank=True, max_length=200, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='revisi',
            field=models.FileField(blank=True, max_length=200, upload_to='pdf/'),
        ),
    ]
