# Generated by Django 4.1.2 on 2022-12-04 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0024_alter_file_jurnal_alter_file_lembar_ta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], max_length=100, null=True)),
                ('mahasiswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.profil_mahasiswa')),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.proposal')),
            ],
        ),
    ]
