# Generated by Django 4.1.2 on 2022-12-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0025_proposal_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal_order',
            name='proposal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.proposal'),
        ),
        migrations.AlterField(
            model_name='proposal_order',
            name='status',
            field=models.CharField(choices=[('Diterima', 'Diterima'), ('Ditolak', 'Ditolak'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
    ]
