# Generated by Django 4.1.2 on 2022-12-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0028_user_kelas_nilai_delete_nilai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_kelas',
            name='nilai',
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='nilai',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
