# Generated by Django 4.1.2 on 2022-12-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0030_alter_proposal_order_mahasiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Sempro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('nim', models.IntegerField(null=True)),
                ('kelas', models.CharField(max_length=50, null=True)),
                ('tanggal', models.DateField(null=True)),
                ('jam', models.TimeField(null=True)),
                ('pbb1', models.CharField(max_length=50, null=True)),
                ('pbb2', models.CharField(max_length=50, null=True)),
                ('judul', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
