# Generated by Django 4.1.2 on 2022-12-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0031_alter_file_user_alter_proposal_user_sempro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sempro',
            name='file',
            field=models.FileField(blank=True, max_length=200, upload_to='pdf/'),
        ),
    ]
