# Generated by Django 4.1.2 on 2022-12-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0033_rename_file_sempro_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sempro',
            name='jam',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sempro',
            name='tanggal',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
