# Generated by Django 4.1.2 on 2022-12-12 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0034_alter_sempro_jam_alter_sempro_tanggal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposal_Order',
            new_name='Order',
        ),
        migrations.AlterField(
            model_name='sempro',
            name='jam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sempro',
            name='judul',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sempro',
            name='tanggal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
