# Generated by Django 4.1.2 on 2022-12-16 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0035_rename_proposal_order_order_alter_sempro_jam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sempro',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_kelas',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mahasiswa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DaftarSidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('nim', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('kelas', models.CharField(max_length=100, null=True)),
                ('prodi', models.CharField(max_length=100, null=True)),
                ('pbb1', models.CharField(max_length=100, null=True)),
                ('pbb2', models.CharField(max_length=100, null=True)),
                ('pemeriksa1', models.CharField(max_length=100, null=True)),
                ('pemeriksa2', models.CharField(max_length=100, null=True)),
                ('tanggal', models.DateField(max_length=200, null=True)),
                ('waktu', models.CharField(max_length=100, null=True)),
                ('tak', models.IntegerField(null=True)),
                ('eprt', models.IntegerField(null=True)),
                ('judul_bahasa', models.CharField(max_length=400, null=True)),
                ('judul_english', models.CharField(max_length=400, null=True)),
                ('email2', models.CharField(max_length=200, null=True)),
                ('whatsapp', models.BigIntegerField(null=True)),
                ('persetujuan', models.CharField(max_length=10, null=True)),
                ('berkas', models.FileField(max_length=200, upload_to='pdf/sidang/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
