# Generated by Django 4.1.2 on 2022-12-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0037_alter_daftarsidang_user_alter_file_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mahasiswa',
            new_name='user',
        ),
    ]
