# Generated by Django 4.1.2 on 2022-12-18 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0038_rename_mahasiswa_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='kelas',
            name='angkatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.angkatan'),
        ),
        migrations.AddField(
            model_name='user_kelas',
            name='angkatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.angkatan'),
        ),
    ]
