# Generated by Django 4.1.2 on 2022-12-18 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0039_angkatan_kelas_angkatan_user_kelas_angkatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_kelas',
            name='angkatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.angkatan'),
        ),
        migrations.AlterField(
            model_name='user_kelas',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.kelas'),
        ),
        migrations.AlterField(
            model_name='user_kelas',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
