# Generated by Django 4.1.2 on 2022-12-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0040_alter_user_kelas_angkatan_alter_user_kelas_kelas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftarsidang',
            name='email2',
        ),
    ]
