# Generated by Django 4.1.2 on 2022-12-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0042_rename_judul_bahasa_daftarsidang_judul_indo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftarsidang',
            old_name='waktu',
            new_name='waktu_sidang',
        ),
        migrations.RemoveField(
            model_name='daftarsidang',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='daftarsidang',
            name='tanggal_sidang',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
