# Generated by Django 4.1.2 on 2022-12-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0043_rename_waktu_daftarsidang_waktu_sidang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarsidang',
            name='persetujuan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
