# Generated by Django 4.1.2 on 2022-12-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0044_alter_daftarsidang_persetujuan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil_mahasiswa',
            old_name='nilai',
            new_name='nilai_proposal',
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='berkas_nilai',
            field=models.FileField(blank=True, max_length=200, upload_to='pdf/nilai'),
        ),
        migrations.AlterField(
            model_name='file',
            name='jurnal',
            field=models.FileField(blank=True, max_length=200, upload_to='pdf/jurnal'),
        ),
        migrations.AlterField(
            model_name='file',
            name='lembar_ta',
            field=models.FileField(blank=True, max_length=200, upload_to='pdf/lembar_ta'),
        ),
        migrations.AlterField(
            model_name='file',
            name='revisi',
            field=models.FileField(blank=True, max_length=200, upload_to='pdf/revisi'),
        ),
    ]
