# Generated by Django 4.1.2 on 2022-12-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0045_rename_nilai_profil_mahasiswa_nilai_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.proposal'),
        ),
        migrations.AlterField(
            model_name='profil_mahasiswa',
            name='berkas_nilai',
            field=models.FileField(max_length=200, upload_to='pdf/nilai'),
        ),
    ]
