# Generated by Django 4.1.2 on 2022-12-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0046_alter_order_proposal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='proposal',
        ),
        migrations.AddField(
            model_name='order',
            name='proposal',
            field=models.ManyToManyField(null=True, to='web_app.proposal'),
        ),
    ]
