# Generated by Django 4.1.2 on 2022-12-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0047_remove_order_proposal_order_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='proposal',
        ),
        migrations.AddField(
            model_name='order',
            name='proposal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.proposal'),
        ),
    ]
