# Generated by Django 4.1.2 on 2022-12-24 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0048_remove_order_proposal_order_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_performance', models.IntegerField(blank=True, null=True)),
                ('CD_1', models.IntegerField(blank=True, null=True)),
                ('CD_2', models.IntegerField(blank=True, null=True)),
                ('CD_3', models.IntegerField(blank=True, null=True)),
                ('presentation', models.IntegerField(blank=True, null=True)),
                ('mahasiswa', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.profil_mahasiswa')),
            ],
        ),
    ]
