# Generated by Django 4.1.2 on 2022-12-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0050_profil_mahasiswa_cd_1_profil_mahasiswa_cd_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil_mahasiswa',
            name='nilai_proposal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
