# Generated by Django 4.1.2 on 2022-12-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0051_alter_profil_mahasiswa_nilai_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuangSidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruang', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='profil_staff',
            old_name='keahlian',
            new_name='kelompok_keahlian',
        ),
        migrations.AddField(
            model_name='daftarsidang',
            name='kelompok_keahlian',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
