# Generated by Django 4.1.2 on 2023-01-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0051_alter_profil_mahasiswa_nilai_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanggal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
