# Generated by Django 4.1.2 on 2022-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0052_ruangsidang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil_staff',
            name='kelompok_keahlian',
            field=models.CharField(choices=[('Seculab', 'Diterima'), ('SEA', 'SEA'), ('Rnest', 'Rnest'), ('Magics', 'Magics'), ('I-Smile', 'I-Smile'), ('Evconn', 'Evconn')], max_length=200, null=True),
        ),
    ]
