# Generated by Django 4.1.2 on 2023-01-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0052_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanggal',
            name='jam',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
