# Generated by Django 4.1.2 on 2023-01-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0053_tanggal_jam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tanggal',
            new_name='inputJadwalSempro',
        ),
    ]
