# Generated by Django 4.1.2 on 2022-12-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0055_alter_profil_staff_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil_staff',
            name='nip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
