# Generated by Django 4.1.2 on 2023-01-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0057_jadwalsidang_jadwalkelasdosen_bebanpengujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarsidang',
            name='hari_sidang',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
