# Generated by Django 4.1.2 on 2023-01-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0060_remove_jadwalsidang_daftar_sidang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalsidang',
            name='tanggal_sidang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jadwalsidang',
            name='hari',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jadwalsidang',
            name='waktu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
