# Generated by Django 4.1.2 on 2023-01-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0065_remove_jadwalsidang_peserta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JadwalSidang',
        ),
    ]
