# Generated by Django 4.1.2 on 2023-01-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0067_jadwalsidang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftarsidang',
            name='pemeriksa1',
        ),
        migrations.RemoveField(
            model_name='daftarsidang',
            name='pemeriksa2',
        ),
    ]
