# Generated by Django 4.1.2 on 2023-01-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0068_remove_daftarsidang_pemeriksa1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='jml_mhs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='judul',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='lab',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pbb1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pbb2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
