# Generated by Django 4.1.2 on 2023-01-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0054_rename_tanggal_inputjadwalsempro'),
        ('web_app', '0070_alter_order_proposal'),
    ]

    operations = [
    ]
