# Generated by Django 4.1.2 on 2023-01-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0072_delete_inputjadwalsempro_alter_order_proposal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BebanPengujian',
        ),
    ]
