# Generated by Django 4.1.2 on 2023-01-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0076_jadwalsemprodosen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwalsemprodosen',
            old_name='dosen',
            new_name='user',
        ),
    ]
