# Generated by Django 4.1.2 on 2023-01-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0079_cd3_cd2_cd1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cd2',
            old_name='cd1',
            new_name='cd2',
        ),
        migrations.RenameField(
            model_name='cd3',
            old_name='cd1',
            new_name='cd3',
        ),
    ]
