# Generated by Django 4.1.2 on 2023-01-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0080_rename_cd1_cd2_cd2_rename_cd1_cd3_cd3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd1',
            name='berkas',
            field=models.FileField(max_length=200, null=True, upload_to='pdf/CD1/'),
        ),
        migrations.AddField(
            model_name='cd2',
            name='berkas',
            field=models.FileField(max_length=200, null=True, upload_to='pdf/CD2/'),
        ),
        migrations.AddField(
            model_name='cd3',
            name='berkas',
            field=models.FileField(max_length=200, null=True, upload_to='pdf/CD3/'),
        ),
    ]
