# Generated by Django 4.1.2 on 2023-01-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0081_cd1_berkas_cd2_berkas_cd3_berkas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd1',
            name='cd1',
        ),
        migrations.RemoveField(
            model_name='cd2',
            name='cd2',
        ),
        migrations.RemoveField(
            model_name='cd3',
            name='cd3',
        ),
    ]
