# Generated by Django 4.1.2 on 2023-01-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0082_remove_cd1_cd1_remove_cd2_cd2_remove_cd3_cd3'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='buku_ta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='final_report',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='individual_performance_ta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='nilai_ta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='paper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='presentasi_demo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='progress_report',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='sidang_ta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sempro',
            name='proposal',
            field=models.FileField(blank=True, max_length=200, upload_to='pdf/sempro'),
        ),
    ]
