# Generated by Django 4.1.2 on 2023-01-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0083_profil_mahasiswa_buku_ta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil_mahasiswa',
            name='nilai_ta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
