# Generated by Django 4.1.2 on 2023-01-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0084_alter_profil_mahasiswa_nilai_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='batas_revisi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='revisi',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
