# Generated by Django 4.1.2 on 2023-01-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0085_profil_mahasiswa_batas_revisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil_mahasiswa',
            name='revisi',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
