# Generated by Django 4.1.2 on 2023-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0087_alter_profil_mahasiswa_revisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarsidang',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
