# Generated by Django 4.1.2 on 2023-01-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0088_daftarsidang_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sempro',
            name='proposal',
        ),
        migrations.AddField(
            model_name='sempro',
            name='cd1',
            field=models.FileField(max_length=200, null=True, upload_to='pdf/CD1/'),
        ),
        migrations.AddField(
            model_name='sempro',
            name='cd2',
            field=models.FileField(max_length=200, null=True, upload_to='pdf/CD2/'),
        ),
        migrations.AddField(
            model_name='sempro',
            name='cd3',
            field=models.FileField(max_length=200, null=True, upload_to='pdf/CD3/'),
        ),
    ]
