# Generated by Django 4.1.2 on 2023-01-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0089_remove_sempro_proposal_sempro_cd1_sempro_cd2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarsidang',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jadwalsidang',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
