# Generated by Django 4.1.2 on 2023-02-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0090_daftarsidang_date_created_jadwalsidang_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='hari_ini',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profil_mahasiswa',
            name='judul_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
