# Generated by Django 4.1.2 on 2023-02-15 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0093_jadwalsemprodosen_jam_mulai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalsemprodosen',
            name='jam_mulai',
        ),
        migrations.RemoveField(
            model_name='jadwalsemprodosen',
            name='jam_selesai',
        ),
        migrations.CreateModel(
            name='JamSemproDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_mulai', models.CharField(max_length=200, null=True)),
                ('jam_selesai', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
